Index: sundials-2.4.0/examples/cvode/fcmix_parallel/Makefile.in
===================================================================
--- sundials-2.4.0.orig/examples/cvode/fcmix_parallel/Makefile.in	2009-05-10 02:22:28.000000000 +0200
+++ sundials-2.4.0/examples/cvode/fcmix_parallel/Makefile.in	2010-03-02 13:40:30.000000000 +0100
@@ -84,7 +84,7 @@
 	$(INSTALL_FILE) $(top_srcdir)/examples/cvode/fcmix_parallel/README  $(EXS_INSTDIR)/cvode/fcmix_parallel/
 	for i in ${EXAMPLES} ; do \
 	  $(INSTALL_FILE) $(top_srcdir)/examples/cvode/fcmix_parallel/$${i}.f   $(EXS_INSTDIR)/cvode/fcmix_parallel/ ; \
-	  $(INSTALL_FILE) $(top_srcdir)/examples/cvode/fcmix_parallel/$${i}.out $(EXS_INSTDIR)/cvode/fcmix_parallel/ ; \
+	  $(INSTALL_FILE) $(top_srcdir)/examples/cvode/fcmix_parallel/$${i} $(EXS_INSTDIR)/cvode/fcmix_parallel/ ; \
 	done
 
 uninstall:
@@ -92,7 +92,7 @@
 	rm -f $(EXS_INSTDIR)/cvode/fcmix_parallel/README
 	for i in ${EXAMPLES} ; do \
 	  rm -f $(EXS_INSTDIR)/cvode/fcmix_parallel/$${i}.f ; \
-	  rm -f $(EXS_INSTDIR)/cvode/fcmix_parallel/$${i}.out ; \
+	  rm -f $(EXS_INSTDIR)/cvode/fcmix_parallel/$${i} ; \
 	done
 	$(rminstalldirs) $(EXS_INSTDIR)/cvode/fcmix_parallel
 	$(rminstalldirs) $(EXS_INSTDIR)/cvode
Index: sundials-2.4.0/examples/cvode/fcmix_serial/Makefile.in
===================================================================
--- sundials-2.4.0.orig/examples/cvode/fcmix_serial/Makefile.in	2009-05-10 02:22:28.000000000 +0200
+++ sundials-2.4.0/examples/cvode/fcmix_serial/Makefile.in	2010-03-02 13:40:30.000000000 +0100
@@ -93,12 +93,12 @@
 	$(INSTALL_FILE) $(top_srcdir)/examples/cvode/fcmix_serial/README $(EXS_INSTDIR)/cvode/fcmix_serial/
 	for i in ${EXAMPLES} ; do \
 	  $(INSTALL_FILE) $(top_srcdir)/examples/cvode/fcmix_serial/$${i}.f   $(EXS_INSTDIR)/cvode/fcmix_serial/ ; \
-	  $(INSTALL_FILE) $(top_srcdir)/examples/cvode/fcmix_serial/$${i}.out $(EXS_INSTDIR)/cvode/fcmix_serial/ ; \
+	  $(INSTALL_FILE) $(top_srcdir)/examples/cvode/fcmix_serial/$${i} $(EXS_INSTDIR)/cvode/fcmix_serial/ ; \
 	done
 	@if test "X${LAPACK_ENABLED}" = "Xyes"; then \
 	for i in ${EXAMPLES_BL} ; do \
 	  $(INSTALL_FILE) $(top_srcdir)/examples/cvode/fcmix_serial/$${i}.f   $(EXS_INSTDIR)/cvode/fcmix_serial/ ; \
-	  $(INSTALL_FILE) $(top_srcdir)/examples/cvode/fcmix_serial/$${i}.out $(EXS_INSTDIR)/cvode/fcmix_serial/ ; \
+	  $(INSTALL_FILE) $(top_srcdir)/examples/cvode/fcmix_serial/$${i} $(EXS_INSTDIR)/cvode/fcmix_serial/ ; \
 	done ; \
 	fi
 
@@ -107,12 +107,12 @@
 	rm -f $(EXS_INSTDIR)/cvode/fcmix_serial/README
 	for i in ${EXAMPLES} ; do \
 	  rm -f $(EXS_INSTDIR)/cvode/fcmix_serial/$${i}.f ; \
-	  rm -f $(EXS_INSTDIR)/cvode/fcmix_serial/$${i}.out ; \
+	  rm -f $(EXS_INSTDIR)/cvode/fcmix_serial/$${i} ; \
 	done
 	@if test "X${LAPACK_ENABLED}" = "Xyes"; then \
 	for i in ${EXAMPLES_BL} ; do \
 	  rm -f $(EXS_INSTDIR)/cvode/fcmix_serial/$${i}.f ; \
-	  rm -f $(EXS_INSTDIR)/cvode/fcmix_serial/$${i}.out ; \
+	  rm -f $(EXS_INSTDIR)/cvode/fcmix_serial/$${i} ; \
 	done ; \
 	fi
 	$(rminstalldirs) $(EXS_INSTDIR)/cvode/fcmix_serial
Index: sundials-2.4.0/examples/cvode/parallel/Makefile.in
===================================================================
--- sundials-2.4.0.orig/examples/cvode/parallel/Makefile.in	2009-05-10 02:22:28.000000000 +0200
+++ sundials-2.4.0/examples/cvode/parallel/Makefile.in	2010-03-02 13:40:30.000000000 +0100
@@ -82,7 +82,7 @@
 	$(INSTALL_FILE) $(top_srcdir)/examples/cvode/parallel/README $(EXS_INSTDIR)/cvode/parallel/
 	for i in ${EXAMPLES} ; do \
 	  $(INSTALL_FILE) $(top_srcdir)/examples/cvode/parallel/$${i}.c   $(EXS_INSTDIR)/cvode/parallel/ ; \
-	  $(INSTALL_FILE) $(top_srcdir)/examples/cvode/parallel/$${i}.out $(EXS_INSTDIR)/cvode/parallel/ ; \
+	  $(INSTALL_FILE) $(top_srcdir)/examples/cvode/parallel/$${i} $(EXS_INSTDIR)/cvode/parallel/ ; \
 	done
 
 uninstall:
@@ -90,7 +90,7 @@
 	rm -f $(EXS_INSTDIR)/cvode/parallel/README
 	for i in ${EXAMPLES} ; do \
 	  rm -f $(EXS_INSTDIR)/cvode/parallel/$${i}.c ; \
-	  rm -f $(EXS_INSTDIR)/cvode/parallel/$${i}.out ; \
+	  rm -f $(EXS_INSTDIR)/cvode/parallel/$${i} ; \
 	done
 	$(rminstalldirs) $(EXS_INSTDIR)/cvode/parallel
 	$(rminstalldirs) $(EXS_INSTDIR)/cvode
Index: sundials-2.4.0/examples/cvode/serial/Makefile.in
===================================================================
--- sundials-2.4.0.orig/examples/cvode/serial/Makefile.in	2009-05-10 02:22:28.000000000 +0200
+++ sundials-2.4.0/examples/cvode/serial/Makefile.in	2010-03-02 13:40:30.000000000 +0100
@@ -96,12 +96,12 @@
 	$(INSTALL_FILE) $(top_srcdir)/examples/cvode/serial/README $(EXS_INSTDIR)/cvode/serial/
 	for i in ${EXAMPLES} ; do \
 	  $(INSTALL_FILE) $(top_srcdir)/examples/cvode/serial/$${i}.c   $(EXS_INSTDIR)/cvode/serial/ ; \
-	  $(INSTALL_FILE) $(top_srcdir)/examples/cvode/serial/$${i}.out $(EXS_INSTDIR)/cvode/serial/ ; \
+	  $(INSTALL_FILE) $(top_srcdir)/examples/cvode/serial/$${i} $(EXS_INSTDIR)/cvode/serial/ ; \
 	done
 	@if test "X${LAPACK_ENABLED}" = "Xyes"; then \
 	for i in ${EXAMPLES_BL} ; do \
 	  $(INSTALL_FILE) $(top_srcdir)/examples/cvode/serial/$${i}.c   $(EXS_INSTDIR)/cvode/serial/ ; \
-	  $(INSTALL_FILE) $(top_srcdir)/examples/cvode/serial/$${i}.out $(EXS_INSTDIR)/cvode/serial/ ; \
+	  $(INSTALL_FILE) $(top_srcdir)/examples/cvode/serial/$${i} $(EXS_INSTDIR)/cvode/serial/ ; \
 	done ; \
 	fi
 
@@ -110,12 +110,12 @@
 	rm -f $(EXS_INSTDIR)/cvode/serial/README
 	for i in ${EXAMPLES} ; do \
 	  rm -f $(EXS_INSTDIR)/cvode/serial/$${i}.c ; \
-	  rm -f $(EXS_INSTDIR)/cvode/serial/$${i}.out ; \
+	  rm -f $(EXS_INSTDIR)/cvode/serial/$${i} ; \
 	done
 	@if test "X${LAPACK_ENABLED}" = "Xyes"; then \
 	for i in ${EXAMPLES_BL} ; do \
 	  rm -f $(EXS_INSTDIR)/cvode/serial/$${i}.c ; \
-	  rm -f $(EXS_INSTDIR)/cvode/serial/$${i}.out ; \
+	  rm -f $(EXS_INSTDIR)/cvode/serial/$${i} ; \
 	done ; \
 	fi
 	$(rminstalldirs) $(EXS_INSTDIR)/cvode/serial
Index: sundials-2.4.0/examples/cvodes/parallel/Makefile.in
===================================================================
--- sundials-2.4.0.orig/examples/cvodes/parallel/Makefile.in	2009-05-10 02:22:36.000000000 +0200
+++ sundials-2.4.0/examples/cvodes/parallel/Makefile.in	2010-03-02 13:40:30.000000000 +0100
@@ -85,7 +85,7 @@
 	$(INSTALL_FILE) $(top_srcdir)/examples/cvodes/parallel/README $(EXS_INSTDIR)/cvodes/parallel/
 	for i in ${EXAMPLES} ; do \
 	  $(INSTALL_FILE) $(top_srcdir)/examples/cvodes/parallel/$${i}.c   $(EXS_INSTDIR)/cvodes/parallel/ ; \
-	  $(INSTALL_FILE) $(top_srcdir)/examples/cvodes/parallel/$${i}.out $(EXS_INSTDIR)/cvodes/parallel/ ; \
+	  $(INSTALL_FILE) $(top_srcdir)/examples/cvodes/parallel/$${i} $(EXS_INSTDIR)/cvodes/parallel/ ; \
 	done
 
 uninstall:
@@ -93,7 +93,7 @@
 	rm -f $(EXS_INSTDIR)/cvodes/parallel/README
 	for i in ${EXAMPLES} ; do \
 	  rm -f $(EXS_INSTDIR)/cvodes/parallel/$${i}.c ; \
-	  rm -f $(EXS_INSTDIR)/cvodes/parallel/$${i}.out ; \
+	  rm -f $(EXS_INSTDIR)/cvodes/parallel/$${i} ; \
 	done
 	$(rminstalldirs) $(EXS_INSTDIR)/cvodes/parallel
 	$(rminstalldirs) $(EXS_INSTDIR)/cvodes
Index: sundials-2.4.0/examples/cvodes/serial/Makefile.in
===================================================================
--- sundials-2.4.0.orig/examples/cvodes/serial/Makefile.in	2009-05-10 02:22:36.000000000 +0200
+++ sundials-2.4.0/examples/cvodes/serial/Makefile.in	2010-03-02 13:40:30.000000000 +0100
@@ -103,12 +103,12 @@
 	$(INSTALL_FILE) $(top_srcdir)/examples/cvodes/serial/README $(EXS_INSTDIR)/cvodes/serial/
 	for i in ${EXAMPLES} ; do \
 	  $(INSTALL_FILE) $(top_srcdir)/examples/cvodes/serial/$${i}.c   $(EXS_INSTDIR)/cvodes/serial/ ; \
-	  $(INSTALL_FILE) $(top_srcdir)/examples/cvodes/serial/$${i}.out $(EXS_INSTDIR)/cvodes/serial/ ; \
+	  $(INSTALL_FILE) $(top_srcdir)/examples/cvodes/serial/$${i} $(EXS_INSTDIR)/cvodes/serial/ ; \
 	done
 	@if test "X${LAPACK_ENABLED}" = "Xyes"; then \
 	for i in ${EXAMPLES_BL} ; do \
 	  $(INSTALL_FILE) $(top_srcdir)/examples/cvodes/serial/$${i}.c   $(EXS_INSTDIR)/cvodes/serial/ ; \
-	  $(INSTALL_FILE) $(top_srcdir)/examples/cvodes/serial/$${i}.out $(EXS_INSTDIR)/cvodes/serial/ ; \
+	  $(INSTALL_FILE) $(top_srcdir)/examples/cvodes/serial/$${i} $(EXS_INSTDIR)/cvodes/serial/ ; \
 	done ; \
 	fi
 
@@ -117,12 +117,12 @@
 	rm -f $(EXS_INSTDIR)/cvodes/serial/README
 	for i in ${EXAMPLES} ; do \
 	  rm -f $(EXS_INSTDIR)/cvodes/serial/$${i}.c ; \
-	  rm -f $(EXS_INSTDIR)/cvodes/serial/$${i}.out ; \
+	  rm -f $(EXS_INSTDIR)/cvodes/serial/$${i} ; \
 	done
 	@if test "X${LAPACK_ENABLED}" = "Xyes"; then \
 	for i in ${EXAMPLES_BL} ; do \
 	  rm -f $(EXS_INSTDIR)/cvodes/serial/$${i}.c ; \
-	  rm -f $(EXS_INSTDIR)/cvodes/serial/$${i}.out ; \
+	  rm -f $(EXS_INSTDIR)/cvodes/serial/$${i} ; \
 	done ; \
 	fi
 	$(rminstalldirs) $(EXS_INSTDIR)/cvodes/serial
Index: sundials-2.4.0/examples/ida/fcmix_parallel/Makefile.in
===================================================================
--- sundials-2.4.0.orig/examples/ida/fcmix_parallel/Makefile.in	2009-05-10 02:22:51.000000000 +0200
+++ sundials-2.4.0/examples/ida/fcmix_parallel/Makefile.in	2010-03-02 13:40:30.000000000 +0100
@@ -82,7 +82,7 @@
 	$(INSTALL_FILE) $(top_srcdir)/examples/ida/fcmix_parallel/README  $(EXS_INSTDIR)/ida/fcmix_parallel/
 	for i in ${EXAMPLES} ; do \
 	  $(INSTALL_FILE) $(top_srcdir)/examples/ida/fcmix_parallel/$${i}.f   $(EXS_INSTDIR)/ida/fcmix_parallel/ ; \
-	  $(INSTALL_FILE) $(top_srcdir)/examples/ida/fcmix_parallel/$${i}.out $(EXS_INSTDIR)/ida/fcmix_parallel/ ; \
+	  $(INSTALL_FILE) $(top_srcdir)/examples/ida/fcmix_parallel/$${i} $(EXS_INSTDIR)/ida/fcmix_parallel/ ; \
 	done
 
 uninstall:
@@ -90,7 +90,7 @@
 	rm -f $(EXS_INSTDIR)/ida/fcmix_parallel/README
 	for i in ${EXAMPLES} ; do \
 	  rm -f $(EXS_INSTDIR)/ida/fcmix_parallel/$${i}.f ; \
-	  rm -f $(EXS_INSTDIR)/ida/fcmix_parallel/$${i}.out ; \
+	  rm -f $(EXS_INSTDIR)/ida/fcmix_parallel/$${i} ; \
 	done
 	$(rminstalldirs) $(EXS_INSTDIR)/ida/fcmix_parallel
 	$(rminstalldirs) $(EXS_INSTDIR)/ida
Index: sundials-2.4.0/examples/ida/fcmix_serial/Makefile.in
===================================================================
--- sundials-2.4.0.orig/examples/ida/fcmix_serial/Makefile.in	2009-05-10 02:22:51.000000000 +0200
+++ sundials-2.4.0/examples/ida/fcmix_serial/Makefile.in	2010-03-02 13:40:30.000000000 +0100
@@ -90,12 +90,12 @@
 	$(INSTALL_FILE) $(top_srcdir)/examples/ida/fcmix_serial/README $(EXS_INSTDIR)/ida/fcmix_serial/
 	for i in ${EXAMPLES} ; do \
 	  $(INSTALL_FILE) $(top_srcdir)/examples/ida/fcmix_serial/$${i}.f   $(EXS_INSTDIR)/ida/fcmix_serial/ ; \
-	  $(INSTALL_FILE) $(top_srcdir)/examples/ida/fcmix_serial/$${i}.out $(EXS_INSTDIR)/ida/fcmix_serial/ ; \
+	  $(INSTALL_FILE) $(top_srcdir)/examples/ida/fcmix_serial/$${i} $(EXS_INSTDIR)/ida/fcmix_serial/ ; \
 	done
 	@if test "X${LAPACK_ENABLED}" = "Xyes"; then \
 	for i in ${EXAMPLES_BL} ; do \
 	  $(INSTALL_FILE) $(top_srcdir)/examples/ida/fcmix_serial/$${i}.f   $(EXS_INSTDIR)/ida/fcmix_serial/ ; \
-	  $(INSTALL_FILE) $(top_srcdir)/examples/ida/fcmix_serial/$${i}.out $(EXS_INSTDIR)/ida/fcmix_serial/ ; \
+	  $(INSTALL_FILE) $(top_srcdir)/examples/ida/fcmix_serial/$${i} $(EXS_INSTDIR)/ida/fcmix_serial/ ; \
 	done ; \
 	fi
 
@@ -104,12 +104,12 @@
 	rm -f $(EXS_INSTDIR)/ida/fcmix_serial/README
 	for i in ${EXAMPLES} ; do \
 	  rm -f $(EXS_INSTDIR)/ida/fcmix_serial/$${i}.f ; \
-	  rm -f $(EXS_INSTDIR)/ida/fcmix_serial/$${i}.out ; \
+	  rm -f $(EXS_INSTDIR)/ida/fcmix_serial/$${i} ; \
 	done
 	@if test "X${LAPACK_ENABLED}" = "Xyes"; then \
 	for i in ${EXAMPLES_BL} ; do \
 	  rm -f $(EXS_INSTDIR)/ida/fcmix_serial/$${i}.f ; \
-	  rm -f $(EXS_INSTDIR)/ida/fcmix_serial/$${i}.out ; \
+	  rm -f $(EXS_INSTDIR)/ida/fcmix_serial/$${i} ; \
 	done ; \
 	fi
 	$(rminstalldirs) $(EXS_INSTDIR)/ida/fcmix_serial
Index: sundials-2.4.0/examples/ida/parallel/Makefile.in
===================================================================
--- sundials-2.4.0.orig/examples/ida/parallel/Makefile.in	2009-05-10 02:22:51.000000000 +0200
+++ sundials-2.4.0/examples/ida/parallel/Makefile.in	2010-03-02 13:40:30.000000000 +0100
@@ -82,7 +82,7 @@
 	$(INSTALL_FILE) $(top_srcdir)/examples/ida/parallel/README $(EXS_INSTDIR)/ida/parallel/
 	for i in ${EXAMPLES} ; do \
 	  $(INSTALL_FILE) $(top_srcdir)/examples/ida/parallel/$${i}.c   $(EXS_INSTDIR)/ida/parallel/ ; \
-	  $(INSTALL_FILE) $(top_srcdir)/examples/ida/parallel/$${i}.out $(EXS_INSTDIR)/ida/parallel/ ; \
+	  $(INSTALL_FILE) $(top_srcdir)/examples/ida/parallel/$${i} $(EXS_INSTDIR)/ida/parallel/ ; \
 	done
 
 uninstall:
@@ -90,7 +90,7 @@
 	rm -f $(EXS_INSTDIR)/ida/parallel/README
 	for i in ${EXAMPLES} ; do \
 	  rm -f $(EXS_INSTDIR)/ida/parallel/$${i}.c ; \
-	  rm -f $(EXS_INSTDIR)/ida/parallel/$${i}.out ; \
+	  rm -f $(EXS_INSTDIR)/ida/parallel/$${i} ; \
 	done
 	$(rminstalldirs) $(EXS_INSTDIR)/ida/parallel
 	$(rminstalldirs) $(EXS_INSTDIR)/ida
Index: sundials-2.4.0/examples/ida/serial/Makefile.in
===================================================================
--- sundials-2.4.0.orig/examples/ida/serial/Makefile.in	2009-05-10 02:22:51.000000000 +0200
+++ sundials-2.4.0/examples/ida/serial/Makefile.in	2010-03-02 13:40:30.000000000 +0100
@@ -91,12 +91,12 @@
 	$(INSTALL_FILE) $(top_srcdir)/examples/ida/serial/README $(EXS_INSTDIR)/ida/serial/
 	for i in ${EXAMPLES} ; do \
 	  $(INSTALL_FILE) $(top_srcdir)/examples/ida/serial/$${i}.c   $(EXS_INSTDIR)/ida/serial/ ; \
-	  $(INSTALL_FILE) $(top_srcdir)/examples/ida/serial/$${i}.out $(EXS_INSTDIR)/ida/serial/ ; \
+	  $(INSTALL_FILE) $(top_srcdir)/examples/ida/serial/$${i} $(EXS_INSTDIR)/ida/serial/ ; \
 	done
 	@if test "X${LAPACK_ENABLED}" = "Xyes"; then \
 	for i in ${EXAMPLES_BL} ; do \
 	  $(INSTALL_FILE) $(top_srcdir)/examples/ida/serial/$${i}.c   $(EXS_INSTDIR)/ida/serial/ ; \
-	  $(INSTALL_FILE) $(top_srcdir)/examples/ida/serial/$${i}.out $(EXS_INSTDIR)/ida/serial/ ; \
+	  $(INSTALL_FILE) $(top_srcdir)/examples/ida/serial/$${i} $(EXS_INSTDIR)/ida/serial/ ; \
 	done ; \
 	fi
 
@@ -105,12 +105,12 @@
 	rm -f $(EXS_INSTDIR)/ida/serial/README
 	for i in ${EXAMPLES} ; do \
 	  rm -f $(EXS_INSTDIR)/ida/serial/$${i}.c ; \
-	  rm -f $(EXS_INSTDIR)/ida/serial/$${i}.out ; \
+	  rm -f $(EXS_INSTDIR)/ida/serial/$${i} ; \
 	done
 	@if test "X${LAPACK_ENABLED}" = "Xyes"; then \
 	for i in ${EXAMPLES_BL} ; do \
 	  rm -f $(EXS_INSTDIR)/ida/serial/$${i}.c ; \
-	  rm -f $(EXS_INSTDIR)/ida/serial/$${i}.out ; \
+	  rm -f $(EXS_INSTDIR)/ida/serial/$${i} ; \
 	done ; \
 	fi
 	$(rminstalldirs) $(EXS_INSTDIR)/ida/serial
Index: sundials-2.4.0/examples/idas/parallel/Makefile.in
===================================================================
--- sundials-2.4.0.orig/examples/idas/parallel/Makefile.in	2009-05-10 02:22:58.000000000 +0200
+++ sundials-2.4.0/examples/idas/parallel/Makefile.in	2010-03-02 13:40:30.000000000 +0100
@@ -86,7 +86,7 @@
 	$(INSTALL_FILE) $(top_srcdir)/examples/idas/parallel/README $(EXS_INSTDIR)/idas/parallel/
 	for i in ${EXAMPLES} ; do \
 	  $(INSTALL_FILE) $(top_srcdir)/examples/idas/parallel/$${i}.c   $(EXS_INSTDIR)/idas/parallel/ ; \
-	  $(INSTALL_FILE) $(top_srcdir)/examples/idas/parallel/$${i}.out $(EXS_INSTDIR)/idas/parallel/ ; \
+	  $(INSTALL_FILE) $(top_srcdir)/examples/idas/parallel/$${i} $(EXS_INSTDIR)/idas/parallel/ ; \
 	done
 
 uninstall:
@@ -94,7 +94,7 @@
 	rm -f $(EXS_INSTDIR)/idas/parallel/README
 	for i in ${EXAMPLES} ; do \
 	  rm -f $(EXS_INSTDIR)/idas/parallel/$${i}.c ; \
-	  rm -f $(EXS_INSTDIR)/idas/parallel/$${i}.out ; \
+	  rm -f $(EXS_INSTDIR)/idas/parallel/$${i} ; \
 	done
 	$(rminstalldirs) $(EXS_INSTDIR)/idas/parallel
 	$(rminstalldirs) $(EXS_INSTDIR)/idas
Index: sundials-2.4.0/examples/idas/serial/Makefile.in
===================================================================
--- sundials-2.4.0.orig/examples/idas/serial/Makefile.in	2009-05-10 02:22:58.000000000 +0200
+++ sundials-2.4.0/examples/idas/serial/Makefile.in	2010-03-02 13:40:30.000000000 +0100
@@ -97,12 +97,12 @@
 	$(INSTALL_FILE) $(top_srcdir)/examples/idas/serial/README $(EXS_INSTDIR)/idas/serial/
 	for i in ${EXAMPLES} ; do \
 	  $(INSTALL_FILE) $(top_srcdir)/examples/idas/serial/$${i}.c   $(EXS_INSTDIR)/idas/serial/ ; \
-	  $(INSTALL_FILE) $(top_srcdir)/examples/idas/serial/$${i}.out $(EXS_INSTDIR)/idas/serial/ ; \
+	  $(INSTALL_FILE) $(top_srcdir)/examples/idas/serial/$${i} $(EXS_INSTDIR)/idas/serial/ ; \
 	done
 	@if test "X${LAPACK_ENABLED}" = "Xyes"; then \
 	for i in ${EXAMPLES_BL} ; do \
 	  $(INSTALL_FILE) $(top_srcdir)/examples/idas/serial/$${i}.c   $(EXS_INSTDIR)/idas/serial/ ; \
-	  $(INSTALL_FILE) $(top_srcdir)/examples/idas/serial/$${i}.out $(EXS_INSTDIR)/idas/serial/ ; \
+	  $(INSTALL_FILE) $(top_srcdir)/examples/idas/serial/$${i} $(EXS_INSTDIR)/idas/serial/ ; \
 	done ; \
 	fi
 
@@ -111,12 +111,12 @@
 	rm -f $(EXS_INSTDIR)/idas/serial/README
 	for i in ${EXAMPLES} ; do \
 	  rm -f $(EXS_INSTDIR)/idas/serial/$${i}.c ; \
-	  rm -f $(EXS_INSTDIR)/idas/serial/$${i}.out ; \
+	  rm -f $(EXS_INSTDIR)/idas/serial/$${i} ; \
 	done
 	@if test "X${LAPACK_ENABLED}" = "Xyes"; then \
 	for i in ${EXAMPLES_BL} ; do \
 	  rm -f $(EXS_INSTDIR)/idas/serial/$${i}.c ; \
-	  rm -f $(EXS_INSTDIR)/idas/serial/$${i}.out ; \
+	  rm -f $(EXS_INSTDIR)/idas/serial/$${i} ; \
 	done ; \
 	fi
 	$(rminstalldirs) $(EXS_INSTDIR)/idas/serial
Index: sundials-2.4.0/examples/kinsol/fcmix_parallel/Makefile.in
===================================================================
--- sundials-2.4.0.orig/examples/kinsol/fcmix_parallel/Makefile.in	2009-05-10 02:23:08.000000000 +0200
+++ sundials-2.4.0/examples/kinsol/fcmix_parallel/Makefile.in	2010-03-02 13:40:30.000000000 +0100
@@ -82,7 +82,7 @@
 	$(INSTALL_FILE) $(top_srcdir)/examples/kinsol/fcmix_parallel/README  $(EXS_INSTDIR)/kinsol/fcmix_parallel/
 	for i in ${EXAMPLES} ; do \
 	  $(INSTALL_FILE) $(top_srcdir)/examples/kinsol/fcmix_parallel/$${i}.f   $(EXS_INSTDIR)/kinsol/fcmix_parallel/ ; \
-	  $(INSTALL_FILE) $(top_srcdir)/examples/kinsol/fcmix_parallel/$${i}.out $(EXS_INSTDIR)/kinsol/fcmix_parallel/ ; \
+	  $(INSTALL_FILE) $(top_srcdir)/examples/kinsol/fcmix_parallel/$${i} $(EXS_INSTDIR)/kinsol/fcmix_parallel/ ; \
 	done
 
 uninstall:
@@ -90,7 +90,7 @@
 	rm -f $(EXS_INSTDIR)/kinsol/fcmix_parallel/README
 	for i in ${EXAMPLES} ; do \
 	  rm -f $(EXS_INSTDIR)/kinsol/fcmix_parallel/$${i}.f ; \
-	  rm -f $(EXS_INSTDIR)/kinsol/fcmix_parallel/$${i}.out ; \
+	  rm -f $(EXS_INSTDIR)/kinsol/fcmix_parallel/$${i} ; \
 	done
 	$(rminstalldirs) $(EXS_INSTDIR)/kinsol/fcmix_parallel
 	$(rminstalldirs) $(EXS_INSTDIR)/kinsol
Index: sundials-2.4.0/examples/kinsol/fcmix_serial/Makefile.in
===================================================================
--- sundials-2.4.0.orig/examples/kinsol/fcmix_serial/Makefile.in	2009-05-10 02:23:08.000000000 +0200
+++ sundials-2.4.0/examples/kinsol/fcmix_serial/Makefile.in	2010-03-02 13:40:30.000000000 +0100
@@ -90,12 +90,12 @@
 	$(INSTALL_FILE) $(top_srcdir)/examples/kinsol/fcmix_serial/README $(EXS_INSTDIR)/kinsol/fcmix_serial/
 	for i in ${EXAMPLES} ; do \
 	  $(INSTALL_FILE) $(top_srcdir)/examples/kinsol/fcmix_serial/$${i}.f   $(EXS_INSTDIR)/kinsol/fcmix_serial/ ; \
-	  $(INSTALL_FILE) $(top_srcdir)/examples/kinsol/fcmix_serial/$${i}.out $(EXS_INSTDIR)/kinsol/fcmix_serial/ ; \
+	  $(INSTALL_FILE) $(top_srcdir)/examples/kinsol/fcmix_serial/$${i} $(EXS_INSTDIR)/kinsol/fcmix_serial/ ; \
 	done
 	@if test "X${LAPACK_ENABLED}" = "Xyes"; then \
 	for i in ${EXAMPLES_BL} ; do \
 	  $(INSTALL_FILE) $(top_srcdir)/examples/kinsol/fcmix_serial/$${i}.f   $(EXS_INSTDIR)/kinsol/fcmix_serial/ ; \
-	  $(INSTALL_FILE) $(top_srcdir)/examples/kinsol/fcmix_serial/$${i}.out $(EXS_INSTDIR)/kinsol/fcmix_serial/ ; \
+	  $(INSTALL_FILE) $(top_srcdir)/examples/kinsol/fcmix_serial/$${i} $(EXS_INSTDIR)/kinsol/fcmix_serial/ ; \
 	done ; \
 	fi
 
@@ -104,12 +104,12 @@
 	rm -f $(EXS_INSTDIR)/kinsol/fcmix_serial/README
 	for i in ${EXAMPLES} ; do \
 	  rm -f $(EXS_INSTDIR)/kinsol/fcmix_serial/$${i}.f ; \
-	  rm -f $(EXS_INSTDIR)/kinsol/fcmix_serial/$${i}.out ; \
+	  rm -f $(EXS_INSTDIR)/kinsol/fcmix_serial/$${i} ; \
 	done
 	@if test "X${LAPACK_ENABLED}" = "Xyes"; then \
 	for i in ${EXAMPLES_BL} ; do \
 	  rm -f $(EXS_INSTDIR)/kinsol/fcmix_serial/$${i}.f ; \
-	  rm -f $(EXS_INSTDIR)/kinsol/fcmix_serial/$${i}.out ; \
+	  rm -f $(EXS_INSTDIR)/kinsol/fcmix_serial/$${i} ; \
 	done ; \
 	fi
 	$(rminstalldirs) $(EXS_INSTDIR)/kinsol/fcmix_serial
Index: sundials-2.4.0/examples/kinsol/parallel/Makefile.in
===================================================================
--- sundials-2.4.0.orig/examples/kinsol/parallel/Makefile.in	2009-05-10 02:23:08.000000000 +0200
+++ sundials-2.4.0/examples/kinsol/parallel/Makefile.in	2010-03-02 13:40:30.000000000 +0100
@@ -80,7 +80,7 @@
 	$(INSTALL_FILE) $(top_srcdir)/examples/kinsol/parallel/README $(EXS_INSTDIR)/kinsol/parallel/
 	for i in ${EXAMPLES} ; do \
 	  $(INSTALL_FILE) $(top_srcdir)/examples/kinsol/parallel/$${i}.c   $(EXS_INSTDIR)/kinsol/parallel/ ; \
-	  $(INSTALL_FILE) $(top_srcdir)/examples/kinsol/parallel/$${i}.out $(EXS_INSTDIR)/kinsol/parallel/ ; \
+	  $(INSTALL_FILE) $(top_srcdir)/examples/kinsol/parallel/$${i} $(EXS_INSTDIR)/kinsol/parallel/ ; \
 	done
 
 uninstall:
@@ -88,7 +88,7 @@
 	rm -f $(EXS_INSTDIR)/kinsol/parallel/README
 	for i in ${EXAMPLES} ; do \
 	  rm -f $(EXS_INSTDIR)/kinsol/parallel/$${i}.c ; \
-	  rm -f $(EXS_INSTDIR)/kinsol/parallel/$${i}.out ; \
+	  rm -f $(EXS_INSTDIR)/kinsol/parallel/$${i} ; \
 	done
 	$(rminstalldirs) $(EXS_INSTDIR)/kinsol/parallel
 	$(rminstalldirs) $(EXS_INSTDIR)/kinsol
Index: sundials-2.4.0/examples/kinsol/serial/Makefile.in
===================================================================
--- sundials-2.4.0.orig/examples/kinsol/serial/Makefile.in	2009-05-10 02:23:08.000000000 +0200
+++ sundials-2.4.0/examples/kinsol/serial/Makefile.in	2010-03-02 13:40:30.000000000 +0100
@@ -90,12 +90,12 @@
 	$(INSTALL_FILE) $(top_srcdir)/examples/kinsol/serial/README $(EXS_INSTDIR)/kinsol/serial/
 	for i in ${EXAMPLES} ; do \
 	  $(INSTALL_FILE) $(top_srcdir)/examples/kinsol/serial/$${i}.c   $(EXS_INSTDIR)/kinsol/serial/ ; \
-	  $(INSTALL_FILE) $(top_srcdir)/examples/kinsol/serial/$${i}.out $(EXS_INSTDIR)/kinsol/serial/ ; \
+	  $(INSTALL_FILE) $(top_srcdir)/examples/kinsol/serial/$${i} $(EXS_INSTDIR)/kinsol/serial/ ; \
 	done
 	@if test "X${LAPACK_ENABLED}" = "Xyes"; then \
 	for i in ${EXAMPLES_BL} ; do \
 	  $(INSTALL_FILE) $(top_srcdir)/examples/kinsol/serial/$${i}.c   $(EXS_INSTDIR)/kinsol/serial/ ; \
-	  $(INSTALL_FILE) $(top_srcdir)/examples/kinsol/serial/$${i}.out $(EXS_INSTDIR)/kinsol/serial/ ; \
+	  $(INSTALL_FILE) $(top_srcdir)/examples/kinsol/serial/$${i} $(EXS_INSTDIR)/kinsol/serial/ ; \
 	done ; \
 	fi
 
@@ -104,12 +104,12 @@
 	rm -f $(EXS_INSTDIR)/kinsol/serial/README
 	for i in ${EXAMPLES} ; do \
 	  rm -f $(EXS_INSTDIR)/kinsol/serial/$${i}.c ; \
-	  rm -f $(EXS_INSTDIR)/kinsol/serial/$${i}.out ; \
+	  rm -f $(EXS_INSTDIR)/kinsol/serial/$${i} ; \
 	done
 	@if test "X${LAPACK_ENABLED}" = "Xyes"; then \
 	for i in ${EXAMPLES_BL} ; do \
 	  rm -f $(EXS_INSTDIR)/kinsol/serial/$${i}.c ; \
-	  rm -f $(EXS_INSTDIR)/kinsol/serial/$${i}.out ; \
+	  rm -f $(EXS_INSTDIR)/kinsol/serial/$${i} ; \
 	done ; \
 	fi
 	$(rminstalldirs) $(EXS_INSTDIR)/kinsol/serial
